use_gpu: True
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 3
  total_round_num: 1000
  save_to: "checkpoints/llama.gsm.offsite_tuning_adpt2_dp0.lr5.fedot.ckpt"
  save_freq: 100
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'gsm8k@llm'
  splits: [0.998,0.001,0.001]
  splitter: 'iid'
llm:
  tok_len: 1000
  chat:
    max_len: 1000
  offsite_tuning:
    use: True
    save_full_model: True
    emu_l: 0
    emu_r: 30
    strategy: 'drop_layer'
    kwargs: [ { 'drop_ratio': 0.0 }]
    emu_align:
      use: True
      initial_only: False
      sim_loss: 'l2'
      layerwise_distill: True
      train:
        local_update_steps: 10
        initial_update_rounds: 50
        lm_loss_weight: 1.0
        kd_loss_weight: 0.0
dataloader:
  batch_size: 1
model:
  type: 'decapoda-research/llama-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.0005
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 100
  metrics: ['loss']
  best_res_update_round_wise_key: 'val_loss'
  report: ['weighted_avg', 'avg', 'raw']
  count_flops: False
expname: "fedot/llama-7b_gsm_offsite_layerwise_adpt2_dp0"