use_gpu: true
device: 2
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 1
  total_round_num: 50
  save_to: /hdd/hdd3/kjb/checkpoints/hhrl_rlhf_gemma_choice_vplgp_ortho_53001.ckpt
  ignore_weight: true
  save_freq: 20
  share_local_model: true
  online_aggr: false
data:
  root: /hdd/hdd3/kjb/
  type: hh-rlhf@llm
  splits:
  - 0.9
  - 0.09
  - 0.01
  splitter: iid
llm:
  use: true
  rlhf: true
  tok_len: 1024
  max_new_token: 512
  num_completions: 2
  accelerator:
    use: false
  chat:
    max_len: 512
  adapter:
    use: true
    count: 3
    warmup:
      use: true
      round: 2
    grouping:
      use: false
      round: 2
    args:
    - adapter_package: peft
      adapter_method: lora
      r: 8
      lora_alpha: 16
      lora_dropout: 0.05
  vpl_latent_dim: 32
  vpl_feature_method: choice_logits
  vpl_use_feature_difference: true
  vpl_use_difference_only: true
  vpl_gp_temperature: 1.0
  rlhf_use_variational_selection: true
  rlhf_use_variational_generation: false
  rlhf_selector_checkpoint: /hdd/hdd3/kjb/checkpoints/final_hhrl_choice_gemma_fedbiscuit_u3_vplgp_ortho_52001.ckpt
  reward_coeff: 0.1
  grad_accum_step: 4
  max_prompts_for_generation: 50
  generation_batch_size: 3
dataloader:
  batch_size: 1
  num_workers: 4
  pin_memory: true
model:
  type: google/gemma-2b@huggingface_llm
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    type: AdamW
    betas:
    - 0.9
    - 0.95
    lr: 0.0001
  is_enable_half: true
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmdporewardtrainer
eval:
  freq: 10
  use_gpt_api_for_winrate: true
  use_baseline_model_for_winrate: true
  metrics: ['loss', 'acc', 'helpfulness_winrate', 'harmlessness_winrate']  # Reward model evaluation disabled
  best_res_update_round_wise_key: train_avg_loss
  count_flops: false
expname: vplgp_hrl_ortho_t53001
wandb:
  use: true
  name_user: ''
  name_project: fvpl-rl
  online_track: true
  client_train_info: true
