use_gpu: True
device: 1
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 1
  total_round_num: 1000
  save_to: "checkpoints/llama.gsm.offsite_tuning.dp2.lr10.central.ckpt"
  save_freq: 500
  share_local_model: False
  online_aggr: False
data:
  root: data/
  type: 'gsm8k@llm'
  splits: [0.998,0.001,0.001]
  splitter: 'iid'
llm:
  tok_len: 1000
  chat:
    max_len: 1000
  offsite_tuning:
    use: True
    emu_l: 2
    emu_r: 30
    strategy: 'drop_layer'
    kwargs: [ { 'drop_ratio': 0.2 }]
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 8, 'lora_alpha': 16, 'lora_dropout': 0.0 } ]
dataloader:
  batch_size: 1
model:
  # type: 'decapoda-research/llama-7b-hf@huggingface_llm'
  type: 'meta-llama/Llama-2-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.001
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 100
  metrics: ['loss']
  best_res_update_round_wise_key: 'test_loss'
  report: ['weighted_avg', 'avg', 'raw']
expname: "central-llm-baselines/llama-7b_gsm8k_offsite-tuning_dp2"